### ISSUE TITLE
Continuous Integration (Linting [tslint], Styling [prettier], Tests [jest])

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcomponents#7]
- [x] Add tslint & prettier to the project.
- [x] Add initial bare-bones tests.
- [x] Run these 3 things for each PR into master.

**Comment by dOrgJelli** [comment]
Project Reference: https://github.com/davidctj/ui-react-module-typescript-storybook-jest

**Comment by dOrgJelli** [comment]
For the tests, here's a short list of things we should ensure are working:
- For all entities they...
  - Render
  - Have Data
  - Have Entities
  - All Inference Works
  - Lists Work
- ConfextFeeds work

**Comment by cbrzn** [comment]
Quick note: We are going to user ESLint because of this https://github.com/palantir/tslint/issues/4534

**Comment by cbrzn** [comment]
For the list component we do:
- Check one element from the list is rendered
- Wait for everything to load (The loading component to disappear)
- We test that there are more than 1 component of the list
